sbatch --job-name=etth1 \
       --output=./scratch/sbatch/etth1.out \
       --error=./scratch/sbatch/etth1.err \
       --nodes=1 \
       --gres=gpu:1 \
       --ntasks-per-node=1 \
       --cpus-per-task=16 \
       --mem=128gb \
       --time=1-00:00:00 \
       --sockets-per-node=1 \
       --cores-per-socket=8 \
       --qos=batch-short \
       --wrap="bash ./scripts/etth1.sh"

sbatch --job-name=ettm1 \
       --output=./scratch/sbatch/ettm1.out \
       --error=./scratch/sbatch/ettm1.err \
       --nodes=1 \
       --gres=gpu:1 \
       --ntasks-per-node=1 \
       --cpus-per-task=16 \
       --mem=128gb \
       --time=1-00:00:00 \
       --sockets-per-node=1 \
       --cores-per-socket=8 \
       --qos=batch-short \
       --wrap="bash ./scripts/ettm1.sh"

sbatch --job-name=etth2 \
       --output=./scratch/sbatch/etth2.out \
       --error=./scratch/sbatch/etth2.err \
       --nodes=1 \
       --gres=gpu:1 \
       --ntasks-per-node=1 \
       --cpus-per-task=16 \
       --mem=128gb \
       --time=1-00:00:00 \
       --sockets-per-node=1 \
       --cores-per-socket=8 \
       --qos=batch-short \
       --wrap="bash ./scripts/etth2.sh"

sbatch --job-name=ettm2 \
       --output=./scratch/sbatch/ettm2.out \
       --error=./scratch/sbatch/ettm2.err \
       --nodes=1 \
       --gres=gpu:1 \
       --ntasks-per-node=1 \
       --cpus-per-task=16 \
       --mem=128gb \
       --time=1-00:00:00 \
       --sockets-per-node=1 \
       --cores-per-socket=8 \
       --qos=batch-short \
       --wrap="bash ./scripts/ettm2.sh"